name: CI
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "13.x"
          cache: yarn

      - uses: microsoft/playwright-github-action@v1

      # Install, should be basically instant if cached
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Verify dependencies are hooked up right
      - run: node test/verifyPackageVersions.js

      # Build the packages
      - run: yarn bootstrap
      - run: yarn workspace lingua-franca build

      # Verify it compiles
      - run: yarn compile
      # Run all the package's tests
      - run: yarn test
        env:
          CI: true

  windows:
    runs-on: windows-latest

    steps:
      # Check out, and set up the node infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "13.x"
          cache: yarn

      # Get local dependencies
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - run: yarn bootstrap
      - run: yarn build